name: Test Server

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "pypy3.10", "3.9", "3.10", "3.11", "3.12", "3.13" ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install package
        run: pip install -r requirements.txt
      - name: Run Test
        run: python utils/testServer.py
